{config, inputs, lib, ...}:

let
  cfg = config.programs.iridium;
in 
{
  config = lib.mkIf cfg.enable {
    wayland.windowManager.hyprland = {
      enable = true;
      configType = "lua";

      extraLuaFiles = {
        "default.keybinds" = {
          content = ./config/keybinds.lua;
          autoLoad = true;
        };

        "default.general" = {
          content = ./config/general.lua;
          autoLoad = true;
        };

        "default.env" = {
          content = ./config/env.lua;
          autoLoad = true;
        };

        "default.execs" = {
          content = ./config/execs.lua;
          autoLoad = true;
        };

        "custom.hyprland" = lib.mkIf (cfg.additionalHyprConfig != null){
          content = cfg.additionalHyprConfig;
          autoLoad = true;
        };
      };

      extraConfig = ''
        -- These files where generated by NixOS
      '';
    };
  };
} 
