{config, pkgs, inputs, lib, ...}:
with lib;
let
  cfg = config.programs.iridium;
in 
{
  options.programs.iridium = {
    additionalHyprConfig = mkOption {
      type = types.nullOr types.path;
      default = null;
      description = "Optional path to an additional lua file that contains your configuration";
      example = literalExpression "./custom.lua";
    };
  };

  config = lib.mkIf cfg.enable {
    home.packages = with pkgs; [
      grimblast
      hyprpicker
      satty
    ];

    wayland.windowManager.hyprland = {
      enable = true;
      configType = "lua";

      extraLuaFiles = {
        "default.keybinds" = {
          content = ./config/keybinds.lua;
          autoLoad = true;
        };

        "default.general" = {
          content = ./config/general.lua;
          autoLoad = true;
        };

        "default.env" = {
          content = ./config/env.lua;
          autoLoad = true;
        };

        "default.execs" = {
          content = ./config/execs.lua;
          autoLoad = true;
        };

        "custom.hyprland" = lib.mkIf (cfg.additionalHyprConfig != null){
          content = cfg.additionalHyprConfig;
          autoLoad = true;
        };
      };

      extraConfig = ''
        -- These files were generated by NixOS
        hl.exec_cmd("${pkgs.awww}/bin/awww-daemon")
        hl.exec_cmd('sleep 1 && ${pkgs.awww}/bin/awww img ${if cfg.wallpaper != null then "${cfg.wallpaperDir}/${cfg.wallpaper}" else "$(find ${cfg.wallpaperDir} -type f | shuf -n1)"}')
      '';
    };
  };
} 
